controllers:
    prefix: /{_locale}
    defaults: { _locale: fr }
    requirements: { _locale: fr|en|es }
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
