index:
    path: /
    controller: App\Controller\DefaultController::index

hello:
    path: /hello/{name}
    controller: App\Controller\DefaultController::hello
    defaults: { name: Dawan }
    requirements: { name: '[A-Z][a-z]*' }
    methods: [ GET, POST, PUT ]
